*** Variables ***

${SEARCH_ELEMENT}=    //*[@id="ast-desktop-header"]/div/div/div/div/div[3]/div[2]/div/div/a
${SEARCH_INPUT_ELEMENT}=    //*[@id="search-field"]    
${VALID_SEARCH_ELEMENT}=    //*[@id="primary"]/section/h1
${INVALID_SEARCH_ELEMENT}=    //*[@id="primary"]/section/h1
${EMPTY_SEARCH_ELEMENT}=   //*[@id="primary"]/section/h1
${SPECIAL_CHAR_ELEMENT}=   //*[@id="primary"]/section/h1
${SEARCH_TERM_ELEMENT}=    //*[@id="primary"]/section/h1
${LONG_SEARCH_ELEMENT}=    //*[@id="primary"]/section/h1